// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domains/sms/repository/dao/sms_record.go
//
// Generated by this command:
//
//	mockgen -source=internal/domains/sms/repository/dao/sms_record.go -package=daomocks -destination=internal/domains/sms/repository/dao/mocks/sms_record.mock.go SmsRecordDAO
//

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	dao "github.com/parkhub/api/internal/domains/sms/repository/dao"
	gomock "go.uber.org/mock/gomock"
)

// MockSmsRecordDAO is a mock of SmsRecordDAO interface.
type MockSmsRecordDAO struct {
	ctrl     *gomock.Controller
	recorder *MockSmsRecordDAOMockRecorder
	isgomock struct{}
}

// MockSmsRecordDAOMockRecorder is the mock recorder for MockSmsRecordDAO.
type MockSmsRecordDAOMockRecorder struct {
	mock *MockSmsRecordDAO
}

// NewMockSmsRecordDAO creates a new mock instance.
func NewMockSmsRecordDAO(ctrl *gomock.Controller) *MockSmsRecordDAO {
	mock := &MockSmsRecordDAO{ctrl: ctrl}
	mock.recorder = &MockSmsRecordDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmsRecordDAO) EXPECT() *MockSmsRecordDAOMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockSmsRecordDAO) FindByID(ctx context.Context, id string) (*dao.SmsRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*dao.SmsRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSmsRecordDAOMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSmsRecordDAO)(nil).FindByID), ctx, id)
}

// FindByPhone mocks base method.
func (m *MockSmsRecordDAO) FindByPhone(ctx context.Context, phone string, page, pageSize int) ([]*dao.SmsRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPhone", ctx, phone, page, pageSize)
	ret0, _ := ret[0].([]*dao.SmsRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByPhone indicates an expected call of FindByPhone.
func (mr *MockSmsRecordDAOMockRecorder) FindByPhone(ctx, phone, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPhone", reflect.TypeOf((*MockSmsRecordDAO)(nil).FindByPhone), ctx, phone, page, pageSize)
}

// Insert mocks base method.
func (m *MockSmsRecordDAO) Insert(ctx context.Context, record *dao.SmsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockSmsRecordDAOMockRecorder) Insert(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockSmsRecordDAO)(nil).Insert), ctx, record)
}

// List mocks base method.
func (m *MockSmsRecordDAO) List(ctx context.Context, filter dao.SmsRecordFilter, page, pageSize int) ([]*dao.SmsRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, page, pageSize)
	ret0, _ := ret[0].([]*dao.SmsRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSmsRecordDAOMockRecorder) List(ctx, filter, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSmsRecordDAO)(nil).List), ctx, filter, page, pageSize)
}
