scrape_configs:
  - job_name: parkhub-monolith
    scrape_interval: 15s
    static_configs:
      - targets:
          - monolith:9090
  - job_name: parkhub-sms
    scrape_interval: 15s
    static_configs:
      - targets:
          - sms:9093
  - job_name: parkhub-identity
    scrape_interval: 15s
    static_configs:
      - targets:
          - identity:9092
  - job_name: parkhub-iot
    scrape_interval: 15s
    static_configs:
      - targets:
          - iot:9092
  - job_name: parkhub-parking
    scrape_interval: 15s
    static_configs:
      - targets:
          - parking:9092
  - job_name: apisix
    scrape_interval: 15s
    metrics_path: /apisix/prometheus/metrics
    static_configs:
      - targets:
          - apisix:9091
