// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domains/sms/service/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/domains/sms/service/interface.go -package=servicemocks -destination=internal/domains/sms/service/mocks/sms_service.mock.go SmsService
//

// Package servicemocks is a generated GoMock package.
package servicemocks

import (
	context "context"
	reflect "reflect"

	service "github.com/parkhub/api/internal/domains/sms/service"
	gomock "go.uber.org/mock/gomock"
)

// MockSmsService is a mock of SmsService interface.
type MockSmsService struct {
	ctrl     *gomock.Controller
	recorder *MockSmsServiceMockRecorder
	isgomock struct{}
}

// MockSmsServiceMockRecorder is the mock recorder for MockSmsService.
type MockSmsServiceMockRecorder struct {
	mock *MockSmsService
}

// NewMockSmsService creates a new mock instance.
func NewMockSmsService(ctrl *gomock.Controller) *MockSmsService {
	mock := &MockSmsService{ctrl: ctrl}
	mock.recorder = &MockSmsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmsService) EXPECT() *MockSmsServiceMockRecorder {
	return m.recorder
}

// SendCode mocks base method.
func (m *MockSmsService) SendCode(ctx context.Context, req *service.SendCodeRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCode", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCode indicates an expected call of SendCode.
func (mr *MockSmsServiceMockRecorder) SendCode(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCode", reflect.TypeOf((*MockSmsService)(nil).SendCode), ctx, req)
}

// VerifyCode mocks base method.
func (m *MockSmsService) VerifyCode(ctx context.Context, req *service.VerifyCodeRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCode", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyCode indicates an expected call of VerifyCode.
func (mr *MockSmsServiceMockRecorder) VerifyCode(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCode", reflect.TypeOf((*MockSmsService)(nil).VerifyCode), ctx, req)
}
