// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domains/sms/repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/domains/sms/repository/interface.go -package=repomocks -destination=internal/domains/sms/repository/mocks/repo.mock.go SmsRepository
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/parkhub/api/internal/domains/sms/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSmsRepository is a mock of SmsRepository interface.
type MockSmsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSmsRepositoryMockRecorder
	isgomock struct{}
}

// MockSmsRepositoryMockRecorder is the mock recorder for MockSmsRepository.
type MockSmsRepositoryMockRecorder struct {
	mock *MockSmsRepository
}

// NewMockSmsRepository creates a new mock instance.
func NewMockSmsRepository(ctrl *gomock.Controller) *MockSmsRepository {
	mock := &MockSmsRepository{ctrl: ctrl}
	mock.recorder = &MockSmsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmsRepository) EXPECT() *MockSmsRepositoryMockRecorder {
	return m.recorder
}

// GetCode mocks base method.
func (m *MockSmsRepository) GetCode(ctx context.Context, phone string, purpose domain.SmsPurpose) (*domain.SmsCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCode", ctx, phone, purpose)
	ret0, _ := ret[0].(*domain.SmsCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCode indicates an expected call of GetCode.
func (mr *MockSmsRepositoryMockRecorder) GetCode(ctx, phone, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCode", reflect.TypeOf((*MockSmsRepository)(nil).GetCode), ctx, phone, purpose)
}

// ReleaseRateLimit mocks base method.
func (m *MockSmsRepository) ReleaseRateLimit(ctx context.Context, phone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseRateLimit", ctx, phone)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseRateLimit indicates an expected call of ReleaseRateLimit.
func (mr *MockSmsRepositoryMockRecorder) ReleaseRateLimit(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseRateLimit", reflect.TypeOf((*MockSmsRepository)(nil).ReleaseRateLimit), ctx, phone)
}

// SaveCode mocks base method.
func (m *MockSmsRepository) SaveCode(ctx context.Context, code *domain.SmsCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCode", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCode indicates an expected call of SaveCode.
func (mr *MockSmsRepositoryMockRecorder) SaveCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCode", reflect.TypeOf((*MockSmsRepository)(nil).SaveCode), ctx, code)
}

// SaveSendFailure mocks base method.
func (m *MockSmsRepository) SaveSendFailure(ctx context.Context, phone string, purpose domain.SmsPurpose, providerErr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSendFailure", ctx, phone, purpose, providerErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSendFailure indicates an expected call of SaveSendFailure.
func (mr *MockSmsRepositoryMockRecorder) SaveSendFailure(ctx, phone, purpose, providerErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSendFailure", reflect.TypeOf((*MockSmsRepository)(nil).SaveSendFailure), ctx, phone, purpose, providerErr)
}

// TryReserveRateLimit mocks base method.
func (m *MockSmsRepository) TryReserveRateLimit(ctx context.Context, phone string, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryReserveRateLimit", ctx, phone, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryReserveRateLimit indicates an expected call of TryReserveRateLimit.
func (mr *MockSmsRepositoryMockRecorder) TryReserveRateLimit(ctx, phone, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryReserveRateLimit", reflect.TypeOf((*MockSmsRepository)(nil).TryReserveRateLimit), ctx, phone, ttl)
}

// VerifyAndConsume mocks base method.
func (m *MockSmsRepository) VerifyAndConsume(ctx context.Context, phone string, purpose domain.SmsPurpose, input string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAndConsume", ctx, phone, purpose, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyAndConsume indicates an expected call of VerifyAndConsume.
func (mr *MockSmsRepositoryMockRecorder) VerifyAndConsume(ctx, phone, purpose, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAndConsume", reflect.TypeOf((*MockSmsRepository)(nil).VerifyAndConsume), ctx, phone, purpose, input)
}
