// Code generated by MockGen. DO NOT EDIT.
// Source: ./auth_interface.go
//
// Generated by this command:
//
//	mockgen -source=./auth_interface.go -package=servicemocks -destination=./mocks/auth_service.mock.go AuthService
//

// Package servicemocks is a generated GoMock package.
package servicemocks

import (
	context "context"
	reflect "reflect"

	service "github.com/parkhub/api/internal/domains/identity/service"
	gomock "go.uber.org/mock/gomock"
)

// MockSmsCodeVerifier is a mock of SmsCodeVerifier interface.
type MockSmsCodeVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockSmsCodeVerifierMockRecorder
	isgomock struct{}
}

// MockSmsCodeVerifierMockRecorder is the mock recorder for MockSmsCodeVerifier.
type MockSmsCodeVerifierMockRecorder struct {
	mock *MockSmsCodeVerifier
}

// NewMockSmsCodeVerifier creates a new mock instance.
func NewMockSmsCodeVerifier(ctrl *gomock.Controller) *MockSmsCodeVerifier {
	mock := &MockSmsCodeVerifier{ctrl: ctrl}
	mock.recorder = &MockSmsCodeVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmsCodeVerifier) EXPECT() *MockSmsCodeVerifierMockRecorder {
	return m.recorder
}

// VerifyCode mocks base method.
func (m *MockSmsCodeVerifier) VerifyCode(ctx context.Context, phone, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCode", ctx, phone, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyCode indicates an expected call of VerifyCode.
func (mr *MockSmsCodeVerifierMockRecorder) VerifyCode(ctx, phone, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCode", reflect.TypeOf((*MockSmsCodeVerifier)(nil).VerifyCode), ctx, phone, code)
}

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx context.Context, req *service.LoginRequest) (*service.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(*service.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, req)
}

// Logout mocks base method.
func (m *MockAuthService) Logout(ctx context.Context, req *service.LogoutRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceMockRecorder) Logout(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthService)(nil).Logout), ctx, req)
}

// RefreshToken mocks base method.
func (m *MockAuthService) RefreshToken(ctx context.Context, req *service.RefreshTokenRequest) (*service.RefreshTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, req)
	ret0, _ := ret[0].(*service.RefreshTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthServiceMockRecorder) RefreshToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthService)(nil).RefreshToken), ctx, req)
}

// SmsLogin mocks base method.
func (m *MockAuthService) SmsLogin(ctx context.Context, req *service.SmsLoginRequest) (*service.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SmsLogin", ctx, req)
	ret0, _ := ret[0].(*service.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SmsLogin indicates an expected call of SmsLogin.
func (mr *MockAuthServiceMockRecorder) SmsLogin(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SmsLogin", reflect.TypeOf((*MockAuthService)(nil).SmsLogin), ctx, req)
}
