// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -package=servicemocks -destination=./mocks/tenant_service.mock.go TenantService
//

// Package servicemocks is a generated GoMock package.
package servicemocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/parkhub/api/internal/domains/identity/domain"
	service "github.com/parkhub/api/internal/domains/identity/service"
	gomock "go.uber.org/mock/gomock"
)

// MockParkingLotCounter is a mock of ParkingLotCounter interface.
type MockParkingLotCounter struct {
	ctrl     *gomock.Controller
	recorder *MockParkingLotCounterMockRecorder
	isgomock struct{}
}

// MockParkingLotCounterMockRecorder is the mock recorder for MockParkingLotCounter.
type MockParkingLotCounterMockRecorder struct {
	mock *MockParkingLotCounter
}

// NewMockParkingLotCounter creates a new mock instance.
func NewMockParkingLotCounter(ctrl *gomock.Controller) *MockParkingLotCounter {
	mock := &MockParkingLotCounter{ctrl: ctrl}
	mock.recorder = &MockParkingLotCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParkingLotCounter) EXPECT() *MockParkingLotCounterMockRecorder {
	return m.recorder
}

// CountParkingLots mocks base method.
func (m *MockParkingLotCounter) CountParkingLots(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountParkingLots", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountParkingLots indicates an expected call of CountParkingLots.
func (mr *MockParkingLotCounterMockRecorder) CountParkingLots(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountParkingLots", reflect.TypeOf((*MockParkingLotCounter)(nil).CountParkingLots), ctx)
}

// MockTenantService is a mock of TenantService interface.
type MockTenantService struct {
	ctrl     *gomock.Controller
	recorder *MockTenantServiceMockRecorder
	isgomock struct{}
}

// MockTenantServiceMockRecorder is the mock recorder for MockTenantService.
type MockTenantServiceMockRecorder struct {
	mock *MockTenantService
}

// NewMockTenantService creates a new mock instance.
func NewMockTenantService(ctrl *gomock.Controller) *MockTenantService {
	mock := &MockTenantService{ctrl: ctrl}
	mock.recorder = &MockTenantServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantService) EXPECT() *MockTenantServiceMockRecorder {
	return m.recorder
}

// CreateTenant mocks base method.
func (m *MockTenantService) CreateTenant(ctx context.Context, req *service.CreateTenantRequest) (*domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", ctx, req)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockTenantServiceMockRecorder) CreateTenant(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockTenantService)(nil).CreateTenant), ctx, req)
}

// DeleteTenant mocks base method.
func (m *MockTenantService) DeleteTenant(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenant", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTenant indicates an expected call of DeleteTenant.
func (mr *MockTenantServiceMockRecorder) DeleteTenant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenant", reflect.TypeOf((*MockTenantService)(nil).DeleteTenant), ctx, id)
}

// FreezeTenant mocks base method.
func (m *MockTenantService) FreezeTenant(ctx context.Context, id string) (*domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FreezeTenant", ctx, id)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FreezeTenant indicates an expected call of FreezeTenant.
func (mr *MockTenantServiceMockRecorder) FreezeTenant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FreezeTenant", reflect.TypeOf((*MockTenantService)(nil).FreezeTenant), ctx, id)
}

// GetTenant mocks base method.
func (m *MockTenantService) GetTenant(ctx context.Context, id string) (*domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenant", ctx, id)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenant indicates an expected call of GetTenant.
func (mr *MockTenantServiceMockRecorder) GetTenant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenant", reflect.TypeOf((*MockTenantService)(nil).GetTenant), ctx, id)
}

// GetTenantSummary mocks base method.
func (m *MockTenantService) GetTenantSummary(ctx context.Context) (*service.TenantSummaryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantSummary", ctx)
	ret0, _ := ret[0].(*service.TenantSummaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantSummary indicates an expected call of GetTenantSummary.
func (mr *MockTenantServiceMockRecorder) GetTenantSummary(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantSummary", reflect.TypeOf((*MockTenantService)(nil).GetTenantSummary), ctx)
}

// ListTenants mocks base method.
func (m *MockTenantService) ListTenants(ctx context.Context, req *service.ListTenantsRequest) (*service.TenantListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTenants", ctx, req)
	ret0, _ := ret[0].(*service.TenantListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTenants indicates an expected call of ListTenants.
func (mr *MockTenantServiceMockRecorder) ListTenants(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTenants", reflect.TypeOf((*MockTenantService)(nil).ListTenants), ctx, req)
}

// UnfreezeTenant mocks base method.
func (m *MockTenantService) UnfreezeTenant(ctx context.Context, id string) (*domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfreezeTenant", ctx, id)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnfreezeTenant indicates an expected call of UnfreezeTenant.
func (mr *MockTenantServiceMockRecorder) UnfreezeTenant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfreezeTenant", reflect.TypeOf((*MockTenantService)(nil).UnfreezeTenant), ctx, id)
}

// UpdateTenant mocks base method.
func (m *MockTenantService) UpdateTenant(ctx context.Context, req *service.UpdateTenantRequest) (*domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenant", ctx, req)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTenant indicates an expected call of UpdateTenant.
func (mr *MockTenantServiceMockRecorder) UpdateTenant(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenant", reflect.TypeOf((*MockTenantService)(nil).UpdateTenant), ctx, req)
}
