// Code generated by MockGen. DO NOT EDIT.
// Source: ./tenant.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dao "github.com/parkhub/api/internal/domains/identity/repository/dao"
)

// MockTenantDAO is a mock of TenantDAO interface.
type MockTenantDAO struct {
	ctrl     *gomock.Controller
	recorder *MockTenantDAOMockRecorder
}

// MockTenantDAOMockRecorder is the mock recorder for MockTenantDAO.
type MockTenantDAOMockRecorder struct {
	mock *MockTenantDAO
}

// NewMockTenantDAO creates a new mock instance.
func NewMockTenantDAO(ctrl *gomock.Controller) *MockTenantDAO {
	mock := &MockTenantDAO{ctrl: ctrl}
	mock.recorder = &MockTenantDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantDAO) EXPECT() *MockTenantDAOMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTenantDAO) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTenantDAOMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTenantDAO)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockTenantDAO) FindAll(ctx context.Context, filter dao.TenantFilter, page, pageSize int) ([]*dao.Tenant, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filter, page, pageSize)
	ret0, _ := ret[0].([]*dao.Tenant)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockTenantDAOMockRecorder) FindAll(ctx, filter, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockTenantDAO)(nil).FindAll), ctx, filter, page, pageSize)
}

// FindByID mocks base method.
func (m *MockTenantDAO) FindByID(ctx context.Context, id string) (*dao.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*dao.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTenantDAOMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTenantDAO)(nil).FindByID), ctx, id)
}

// FindByName mocks base method.
func (m *MockTenantDAO) FindByName(ctx context.Context, name string) (*dao.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*dao.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockTenantDAOMockRecorder) FindByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockTenantDAO)(nil).FindByName), ctx, name)
}

// Insert mocks base method.
func (m *MockTenantDAO) Insert(ctx context.Context, tenant *dao.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, tenant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockTenantDAOMockRecorder) Insert(ctx, tenant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockTenantDAO)(nil).Insert), ctx, tenant)
}

// Update mocks base method.
func (m *MockTenantDAO) Update(ctx context.Context, tenant *dao.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tenant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTenantDAOMockRecorder) Update(ctx, tenant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTenantDAO)(nil).Update), ctx, tenant)
}
