// Code generated by MockGen. DO NOT EDIT.
// Source: ./parking_lot.go
//
// Generated by this command:
//
//	mockgen -source=./parking_lot.go -package=daomocks -destination=./mocks/parking_lot.mock.go ParkingLotDAO
//

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	dao "github.com/parkhub/api/internal/domains/parking/repository/dao"
	gomock "go.uber.org/mock/gomock"
)

// MockParkingLotDAO is a mock of ParkingLotDAO interface.
type MockParkingLotDAO struct {
	ctrl     *gomock.Controller
	recorder *MockParkingLotDAOMockRecorder
	isgomock struct{}
}

// MockParkingLotDAOMockRecorder is the mock recorder for MockParkingLotDAO.
type MockParkingLotDAOMockRecorder struct {
	mock *MockParkingLotDAO
}

// NewMockParkingLotDAO creates a new mock instance.
func NewMockParkingLotDAO(ctrl *gomock.Controller) *MockParkingLotDAO {
	mock := &MockParkingLotDAO{ctrl: ctrl}
	mock.recorder = &MockParkingLotDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParkingLotDAO) EXPECT() *MockParkingLotDAOMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockParkingLotDAO) Delete(ctx context.Context, tenantID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockParkingLotDAOMockRecorder) Delete(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockParkingLotDAO)(nil).Delete), ctx, tenantID, id)
}

// FindAll mocks base method.
func (m *MockParkingLotDAO) FindAll(ctx context.Context, filter dao.ParkingLotFilter, page, pageSize int) ([]*dao.ParkingLot, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filter, page, pageSize)
	ret0, _ := ret[0].([]*dao.ParkingLot)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockParkingLotDAOMockRecorder) FindAll(ctx, filter, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockParkingLotDAO)(nil).FindAll), ctx, filter, page, pageSize)
}

// FindByID mocks base method.
func (m *MockParkingLotDAO) FindByID(ctx context.Context, tenantID, id string) (*dao.ParkingLot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, tenantID, id)
	ret0, _ := ret[0].(*dao.ParkingLot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockParkingLotDAOMockRecorder) FindByID(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockParkingLotDAO)(nil).FindByID), ctx, tenantID, id)
}

// Insert mocks base method.
func (m *MockParkingLotDAO) Insert(ctx context.Context, lot *dao.ParkingLot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, lot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockParkingLotDAOMockRecorder) Insert(ctx, lot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockParkingLotDAO)(nil).Insert), ctx, lot)
}

// SumStats mocks base method.
func (m *MockParkingLotDAO) SumStats(ctx context.Context, tenantID string) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumStats", ctx, tenantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SumStats indicates an expected call of SumStats.
func (mr *MockParkingLotDAOMockRecorder) SumStats(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumStats", reflect.TypeOf((*MockParkingLotDAO)(nil).SumStats), ctx, tenantID)
}

// Update mocks base method.
func (m *MockParkingLotDAO) Update(ctx context.Context, lot *dao.ParkingLot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, lot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockParkingLotDAOMockRecorder) Update(ctx, lot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockParkingLotDAO)(nil).Update), ctx, lot)
}
