// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -package=repomocks -destination=./mocks/device_repo.mock.go DeviceRepo
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/parkhub/api/internal/domains/iot/domain"
	repository "github.com/parkhub/api/internal/domains/iot/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceRepo is a mock of DeviceRepo interface.
type MockDeviceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceRepoMockRecorder
	isgomock struct{}
}

// MockDeviceRepoMockRecorder is the mock recorder for MockDeviceRepo.
type MockDeviceRepoMockRecorder struct {
	mock *MockDeviceRepo
}

// NewMockDeviceRepo creates a new mock instance.
func NewMockDeviceRepo(ctrl *gomock.Controller) *MockDeviceRepo {
	mock := &MockDeviceRepo{ctrl: ctrl}
	mock.recorder = &MockDeviceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceRepo) EXPECT() *MockDeviceRepoMockRecorder {
	return m.recorder
}

// CountByStatus mocks base method.
func (m *MockDeviceRepo) CountByStatus(ctx context.Context, tenantID string) (int64, int64, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", ctx, tenantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(int64)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockDeviceRepoMockRecorder) CountByStatus(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockDeviceRepo)(nil).CountByStatus), ctx, tenantID)
}

// Create mocks base method.
func (m *MockDeviceRepo) Create(ctx context.Context, device *domain.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeviceRepoMockRecorder) Create(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceRepo)(nil).Create), ctx, device)
}

// Delete mocks base method.
func (m *MockDeviceRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceRepo)(nil).Delete), ctx, id)
}

// DeleteBatch mocks base method.
func (m *MockDeviceRepo) DeleteBatch(ctx context.Context, ids []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockDeviceRepoMockRecorder) DeleteBatch(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockDeviceRepo)(nil).DeleteBatch), ctx, ids)
}

// GetByID mocks base method.
func (m *MockDeviceRepo) GetByID(ctx context.Context, id string) (*domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDeviceRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeviceRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockDeviceRepo) List(ctx context.Context, filter repository.DeviceFilter, page, pageSize int) ([]*domain.Device, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, page, pageSize)
	ret0, _ := ret[0].([]*domain.Device)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDeviceRepoMockRecorder) List(ctx, filter, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDeviceRepo)(nil).List), ctx, filter, page, pageSize)
}

// UnbindByDeviceIDs mocks base method.
func (m *MockDeviceRepo) UnbindByDeviceIDs(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnbindByDeviceIDs", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnbindByDeviceIDs indicates an expected call of UnbindByDeviceIDs.
func (mr *MockDeviceRepoMockRecorder) UnbindByDeviceIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnbindByDeviceIDs", reflect.TypeOf((*MockDeviceRepo)(nil).UnbindByDeviceIDs), ctx, ids)
}

// Update mocks base method.
func (m *MockDeviceRepo) Update(ctx context.Context, device *domain.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeviceRepoMockRecorder) Update(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeviceRepo)(nil).Update), ctx, device)
}

// UpdateStatus mocks base method.
func (m *MockDeviceRepo) UpdateStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDeviceRepoMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateStatus), ctx, id, status)
}

// UpdateStatusBatch mocks base method.
func (m *MockDeviceRepo) UpdateStatusBatch(ctx context.Context, ids []string, status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusBatch", ctx, ids, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatusBatch indicates an expected call of UpdateStatusBatch.
func (mr *MockDeviceRepoMockRecorder) UpdateStatusBatch(ctx, ids, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusBatch", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateStatusBatch), ctx, ids, status)
}
