// Code generated by MockGen. DO NOT EDIT.
// Source: ./auth_interface.go
//
// Generated by this command:
//
//	mockgen -source=./auth_interface.go -package=repomocks -destination=./mocks/auth_repo.mock.go RefreshTokenRepo
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenRepo is a mock of RefreshTokenRepo interface.
type MockRefreshTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepoMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepoMockRecorder is the mock recorder for MockRefreshTokenRepo.
type MockRefreshTokenRepoMockRecorder struct {
	mock *MockRefreshTokenRepo
}

// NewMockRefreshTokenRepo creates a new mock instance.
func NewMockRefreshTokenRepo(ctrl *gomock.Controller) *MockRefreshTokenRepo {
	mock := &MockRefreshTokenRepo{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepo) EXPECT() *MockRefreshTokenRepoMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockRefreshTokenRepo) Consume(ctx context.Context, jti string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, jti)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Consume indicates an expected call of Consume.
func (mr *MockRefreshTokenRepoMockRecorder) Consume(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockRefreshTokenRepo)(nil).Consume), ctx, jti)
}

// Revoke mocks base method.
func (m *MockRefreshTokenRepo) Revoke(ctx context.Context, jti string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, jti)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshTokenRepoMockRecorder) Revoke(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshTokenRepo)(nil).Revoke), ctx, jti)
}

// Save mocks base method.
func (m *MockRefreshTokenRepo) Save(ctx context.Context, jti, userID string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, jti, userID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRefreshTokenRepoMockRecorder) Save(ctx, jti, userID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRefreshTokenRepo)(nil).Save), ctx, jti, userID, ttl)
}
