// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -package=repomocks -destination=./mocks/repo.mock.go TenantRepo
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/parkhub/api/internal/domains/identity/domain"
	repository "github.com/parkhub/api/internal/domains/identity/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockTenantRepo is a mock of TenantRepo interface.
type MockTenantRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTenantRepoMockRecorder
	isgomock struct{}
}

// MockTenantRepoMockRecorder is the mock recorder for MockTenantRepo.
type MockTenantRepoMockRecorder struct {
	mock *MockTenantRepo
}

// NewMockTenantRepo creates a new mock instance.
func NewMockTenantRepo(ctrl *gomock.Controller) *MockTenantRepo {
	mock := &MockTenantRepo{ctrl: ctrl}
	mock.recorder = &MockTenantRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantRepo) EXPECT() *MockTenantRepoMockRecorder {
	return m.recorder
}

// CountByStatus mocks base method.
func (m *MockTenantRepo) CountByStatus(ctx context.Context) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockTenantRepoMockRecorder) CountByStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockTenantRepo)(nil).CountByStatus), ctx)
}

// Create mocks base method.
func (m *MockTenantRepo) Create(ctx context.Context, tenant *domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tenant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTenantRepoMockRecorder) Create(ctx, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantRepo)(nil).Create), ctx, tenant)
}

// Delete mocks base method.
func (m *MockTenantRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTenantRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTenantRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockTenantRepo) GetByID(ctx context.Context, id string) (*domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTenantRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTenantRepo)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockTenantRepo) GetByName(ctx context.Context, name string) (*domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTenantRepoMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTenantRepo)(nil).GetByName), ctx, name)
}

// List mocks base method.
func (m *MockTenantRepo) List(ctx context.Context, filter repository.TenantFilter, page, pageSize int) ([]*domain.Tenant, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, page, pageSize)
	ret0, _ := ret[0].([]*domain.Tenant)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTenantRepoMockRecorder) List(ctx, filter, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTenantRepo)(nil).List), ctx, filter, page, pageSize)
}

// Update mocks base method.
func (m *MockTenantRepo) Update(ctx context.Context, tenant *domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tenant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTenantRepoMockRecorder) Update(ctx, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTenantRepo)(nil).Update), ctx, tenant)
}
