// Code generated by MockGen. DO NOT EDIT.
// Source: ./device.go
//
// Generated by this command:
//
//	mockgen -source=./device.go -package=daomocks -destination=./mocks/device.mock.go DeviceDAO
//

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"

	dao "github.com/parkhub/api/internal/domains/iot/repository/dao"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceDAO is a mock of DeviceDAO interface.
type MockDeviceDAO struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceDAOMockRecorder
	isgomock struct{}
}

// MockDeviceDAOMockRecorder is the mock recorder for MockDeviceDAO.
type MockDeviceDAOMockRecorder struct {
	mock *MockDeviceDAO
}

// NewMockDeviceDAO creates a new mock instance.
func NewMockDeviceDAO(ctrl *gomock.Controller) *MockDeviceDAO {
	mock := &MockDeviceDAO{ctrl: ctrl}
	mock.recorder = &MockDeviceDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceDAO) EXPECT() *MockDeviceDAOMockRecorder {
	return m.recorder
}

// CountByStatus mocks base method.
func (m *MockDeviceDAO) CountByStatus(ctx context.Context, tenantID string) (int64, int64, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", ctx, tenantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(int64)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockDeviceDAOMockRecorder) CountByStatus(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockDeviceDAO)(nil).CountByStatus), ctx, tenantID)
}

// Delete mocks base method.
func (m *MockDeviceDAO) Delete(ctx context.Context, tenantID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceDAOMockRecorder) Delete(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceDAO)(nil).Delete), ctx, tenantID, id)
}

// DeleteBatch mocks base method.
func (m *MockDeviceDAO) DeleteBatch(ctx context.Context, tenantID string, ids []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, tenantID, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockDeviceDAOMockRecorder) DeleteBatch(ctx, tenantID, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockDeviceDAO)(nil).DeleteBatch), ctx, tenantID, ids)
}

// FindAll mocks base method.
func (m *MockDeviceDAO) FindAll(ctx context.Context, filter dao.DeviceFilter, page, pageSize int) ([]*dao.Device, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filter, page, pageSize)
	ret0, _ := ret[0].([]*dao.Device)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockDeviceDAOMockRecorder) FindAll(ctx, filter, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockDeviceDAO)(nil).FindAll), ctx, filter, page, pageSize)
}

// FindByID mocks base method.
func (m *MockDeviceDAO) FindByID(ctx context.Context, tenantID, id string) (*dao.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, tenantID, id)
	ret0, _ := ret[0].(*dao.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDeviceDAOMockRecorder) FindByID(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDeviceDAO)(nil).FindByID), ctx, tenantID, id)
}

// Insert mocks base method.
func (m *MockDeviceDAO) Insert(ctx context.Context, device *dao.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockDeviceDAOMockRecorder) Insert(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDeviceDAO)(nil).Insert), ctx, device)
}

// UnbindByDeviceIDs mocks base method.
func (m *MockDeviceDAO) UnbindByDeviceIDs(ctx context.Context, tenantID string, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnbindByDeviceIDs", ctx, tenantID, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnbindByDeviceIDs indicates an expected call of UnbindByDeviceIDs.
func (mr *MockDeviceDAOMockRecorder) UnbindByDeviceIDs(ctx, tenantID, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnbindByDeviceIDs", reflect.TypeOf((*MockDeviceDAO)(nil).UnbindByDeviceIDs), ctx, tenantID, ids)
}

// Update mocks base method.
func (m *MockDeviceDAO) Update(ctx context.Context, device *dao.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeviceDAOMockRecorder) Update(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeviceDAO)(nil).Update), ctx, device)
}

// UpdateStatus mocks base method.
func (m *MockDeviceDAO) UpdateStatus(ctx context.Context, tenantID, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, tenantID, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDeviceDAOMockRecorder) UpdateStatus(ctx, tenantID, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDeviceDAO)(nil).UpdateStatus), ctx, tenantID, id, status)
}

// UpdateStatusBatch mocks base method.
func (m *MockDeviceDAO) UpdateStatusBatch(ctx context.Context, tenantID string, ids []string, status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusBatch", ctx, tenantID, ids, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatusBatch indicates an expected call of UpdateStatusBatch.
func (mr *MockDeviceDAOMockRecorder) UpdateStatusBatch(ctx, tenantID, ids, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusBatch", reflect.TypeOf((*MockDeviceDAO)(nil).UpdateStatusBatch), ctx, tenantID, ids, status)
}
