// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -package=repomocks -destination=./mocks/repo.mock.go ParkingLotRepo
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/parkhub/api/internal/domains/parking/domain"
	repository "github.com/parkhub/api/internal/domains/parking/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockParkingLotRepo is a mock of ParkingLotRepo interface.
type MockParkingLotRepo struct {
	ctrl     *gomock.Controller
	recorder *MockParkingLotRepoMockRecorder
	isgomock struct{}
}

// MockParkingLotRepoMockRecorder is the mock recorder for MockParkingLotRepo.
type MockParkingLotRepoMockRecorder struct {
	mock *MockParkingLotRepo
}

// NewMockParkingLotRepo creates a new mock instance.
func NewMockParkingLotRepo(ctrl *gomock.Controller) *MockParkingLotRepo {
	mock := &MockParkingLotRepo{ctrl: ctrl}
	mock.recorder = &MockParkingLotRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParkingLotRepo) EXPECT() *MockParkingLotRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockParkingLotRepo) Create(ctx context.Context, lot *domain.ParkingLot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, lot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockParkingLotRepoMockRecorder) Create(ctx, lot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockParkingLotRepo)(nil).Create), ctx, lot)
}

// Delete mocks base method.
func (m *MockParkingLotRepo) Delete(ctx context.Context, tenantID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockParkingLotRepoMockRecorder) Delete(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockParkingLotRepo)(nil).Delete), ctx, tenantID, id)
}

// GetByID mocks base method.
func (m *MockParkingLotRepo) GetByID(ctx context.Context, tenantID, id string) (*domain.ParkingLot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, tenantID, id)
	ret0, _ := ret[0].(*domain.ParkingLot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockParkingLotRepoMockRecorder) GetByID(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockParkingLotRepo)(nil).GetByID), ctx, tenantID, id)
}

// List mocks base method.
func (m *MockParkingLotRepo) List(ctx context.Context, filter repository.ParkingLotFilter, page, pageSize int) ([]*domain.ParkingLot, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, page, pageSize)
	ret0, _ := ret[0].([]*domain.ParkingLot)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockParkingLotRepoMockRecorder) List(ctx, filter, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockParkingLotRepo)(nil).List), ctx, filter, page, pageSize)
}

// SumStats mocks base method.
func (m *MockParkingLotRepo) SumStats(ctx context.Context, tenantID string) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumStats", ctx, tenantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SumStats indicates an expected call of SumStats.
func (mr *MockParkingLotRepoMockRecorder) SumStats(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumStats", reflect.TypeOf((*MockParkingLotRepo)(nil).SumStats), ctx, tenantID)
}

// Update mocks base method.
func (m *MockParkingLotRepo) Update(ctx context.Context, lot *domain.ParkingLot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, lot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockParkingLotRepoMockRecorder) Update(ctx, lot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockParkingLotRepo)(nil).Update), ctx, lot)
}
