// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -package=servicemocks -destination=./mocks/parking_lot_service.mock.go ParkingLotService
//

// Package servicemocks is a generated GoMock package.
package servicemocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/parkhub/api/internal/domains/parking/domain"
	service "github.com/parkhub/api/internal/domains/parking/service"
	gomock "go.uber.org/mock/gomock"
)

// MockParkingLotService is a mock of ParkingLotService interface.
type MockParkingLotService struct {
	ctrl     *gomock.Controller
	recorder *MockParkingLotServiceMockRecorder
	isgomock struct{}
}

// MockParkingLotServiceMockRecorder is the mock recorder for MockParkingLotService.
type MockParkingLotServiceMockRecorder struct {
	mock *MockParkingLotService
}

// NewMockParkingLotService creates a new mock instance.
func NewMockParkingLotService(ctrl *gomock.Controller) *MockParkingLotService {
	mock := &MockParkingLotService{ctrl: ctrl}
	mock.recorder = &MockParkingLotServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParkingLotService) EXPECT() *MockParkingLotServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockParkingLotService) Create(ctx context.Context, req *service.CreateParkingLotRequest) (*domain.ParkingLot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*domain.ParkingLot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockParkingLotServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockParkingLotService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockParkingLotService) Delete(ctx context.Context, tenantID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockParkingLotServiceMockRecorder) Delete(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockParkingLotService)(nil).Delete), ctx, tenantID, id)
}

// GetByID mocks base method.
func (m *MockParkingLotService) GetByID(ctx context.Context, tenantID, id string) (*domain.ParkingLot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, tenantID, id)
	ret0, _ := ret[0].(*domain.ParkingLot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockParkingLotServiceMockRecorder) GetByID(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockParkingLotService)(nil).GetByID), ctx, tenantID, id)
}

// GetStats mocks base method.
func (m *MockParkingLotService) GetStats(ctx context.Context, tenantID string) (*service.ParkingLotStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, tenantID)
	ret0, _ := ret[0].(*service.ParkingLotStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockParkingLotServiceMockRecorder) GetStats(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockParkingLotService)(nil).GetStats), ctx, tenantID)
}

// List mocks base method.
func (m *MockParkingLotService) List(ctx context.Context, req *service.ListParkingLotsRequest) (*service.ParkingLotListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].(*service.ParkingLotListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockParkingLotServiceMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockParkingLotService)(nil).List), ctx, req)
}

// Update mocks base method.
func (m *MockParkingLotService) Update(ctx context.Context, req *service.UpdateParkingLotRequest) (*domain.ParkingLot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*domain.ParkingLot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockParkingLotServiceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockParkingLotService)(nil).Update), ctx, req)
}
