// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -package=servicemocks -destination=./mocks/device_service.mock.go DeviceService
//

// Package servicemocks is a generated GoMock package.
package servicemocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/parkhub/api/internal/domains/iot/domain"
	service "github.com/parkhub/api/internal/domains/iot/service"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceService is a mock of DeviceService interface.
type MockDeviceService struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceServiceMockRecorder
	isgomock struct{}
}

// MockDeviceServiceMockRecorder is the mock recorder for MockDeviceService.
type MockDeviceServiceMockRecorder struct {
	mock *MockDeviceService
}

// NewMockDeviceService creates a new mock instance.
func NewMockDeviceService(ctrl *gomock.Controller) *MockDeviceService {
	mock := &MockDeviceService{ctrl: ctrl}
	mock.recorder = &MockDeviceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceService) EXPECT() *MockDeviceServiceMockRecorder {
	return m.recorder
}

// BatchBind mocks base method.
func (m *MockDeviceService) BatchBind(ctx context.Context, req *service.BatchBindDeviceRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchBind", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchBind indicates an expected call of BatchBind.
func (mr *MockDeviceServiceMockRecorder) BatchBind(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchBind", reflect.TypeOf((*MockDeviceService)(nil).BatchBind), ctx, req)
}

// BatchDelete mocks base method.
func (m *MockDeviceService) BatchDelete(ctx context.Context, req *service.BatchDeleteDeviceRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockDeviceServiceMockRecorder) BatchDelete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockDeviceService)(nil).BatchDelete), ctx, req)
}

// BatchDisable mocks base method.
func (m *MockDeviceService) BatchDisable(ctx context.Context, req *service.BatchChangeDeviceStatusRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDisable", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDisable indicates an expected call of BatchDisable.
func (mr *MockDeviceServiceMockRecorder) BatchDisable(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDisable", reflect.TypeOf((*MockDeviceService)(nil).BatchDisable), ctx, req)
}

// BatchEnable mocks base method.
func (m *MockDeviceService) BatchEnable(ctx context.Context, req *service.BatchChangeDeviceStatusRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchEnable", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchEnable indicates an expected call of BatchEnable.
func (mr *MockDeviceServiceMockRecorder) BatchEnable(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchEnable", reflect.TypeOf((*MockDeviceService)(nil).BatchEnable), ctx, req)
}

// Bind mocks base method.
func (m *MockDeviceService) Bind(ctx context.Context, req *service.BindDeviceRequest) (*domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bind", ctx, req)
	ret0, _ := ret[0].(*domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Bind indicates an expected call of Bind.
func (mr *MockDeviceServiceMockRecorder) Bind(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockDeviceService)(nil).Bind), ctx, req)
}

// Create mocks base method.
func (m *MockDeviceService) Create(ctx context.Context, req *service.CreateDeviceRequest) (*domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDeviceServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockDeviceService) Delete(ctx context.Context, req *service.DeleteDeviceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceServiceMockRecorder) Delete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceService)(nil).Delete), ctx, req)
}

// Disable mocks base method.
func (m *MockDeviceService) Disable(ctx context.Context, req *service.ChangeDeviceStatusRequest) (*domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, req)
	ret0, _ := ret[0].(*domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Disable indicates an expected call of Disable.
func (mr *MockDeviceServiceMockRecorder) Disable(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockDeviceService)(nil).Disable), ctx, req)
}

// Enable mocks base method.
func (m *MockDeviceService) Enable(ctx context.Context, req *service.ChangeDeviceStatusRequest) (*domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable", ctx, req)
	ret0, _ := ret[0].(*domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enable indicates an expected call of Enable.
func (mr *MockDeviceServiceMockRecorder) Enable(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockDeviceService)(nil).Enable), ctx, req)
}

// GetByID mocks base method.
func (m *MockDeviceService) GetByID(ctx context.Context, req *service.GetDeviceRequest) (*domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, req)
	ret0, _ := ret[0].(*domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDeviceServiceMockRecorder) GetByID(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeviceService)(nil).GetByID), ctx, req)
}

// GetStats mocks base method.
func (m *MockDeviceService) GetStats(ctx context.Context, tenantID string) (*service.DeviceStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, tenantID)
	ret0, _ := ret[0].(*service.DeviceStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockDeviceServiceMockRecorder) GetStats(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockDeviceService)(nil).GetStats), ctx, tenantID)
}

// List mocks base method.
func (m *MockDeviceService) List(ctx context.Context, req *service.ListDevicesRequest) (*service.DeviceListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].(*service.DeviceListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDeviceServiceMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDeviceService)(nil).List), ctx, req)
}

// SendCommand mocks base method.
func (m *MockDeviceService) SendCommand(ctx context.Context, tenantID, deviceID, action string) (*service.CommandResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCommand", ctx, tenantID, deviceID, action)
	ret0, _ := ret[0].(*service.CommandResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendCommand indicates an expected call of SendCommand.
func (mr *MockDeviceServiceMockRecorder) SendCommand(ctx, tenantID, deviceID, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCommand", reflect.TypeOf((*MockDeviceService)(nil).SendCommand), ctx, tenantID, deviceID, action)
}

// Unbind mocks base method.
func (m *MockDeviceService) Unbind(ctx context.Context, req *service.UnbindDeviceRequest) (*domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unbind", ctx, req)
	ret0, _ := ret[0].(*domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unbind indicates an expected call of Unbind.
func (mr *MockDeviceServiceMockRecorder) Unbind(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unbind", reflect.TypeOf((*MockDeviceService)(nil).Unbind), ctx, req)
}

// UpdateName mocks base method.
func (m *MockDeviceService) UpdateName(ctx context.Context, req *service.UpdateDeviceNameRequest) (*domain.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateName", ctx, req)
	ret0, _ := ret[0].(*domain.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateName indicates an expected call of UpdateName.
func (mr *MockDeviceServiceMockRecorder) UpdateName(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateName", reflect.TypeOf((*MockDeviceService)(nil).UpdateName), ctx, req)
}
