// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domains/sms/repository/cache/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/domains/sms/repository/cache/interface.go -package=cachemocks -destination=internal/domains/sms/repository/cache/mocks/sms_cache.mock.go SmsCache
//

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/parkhub/api/internal/domains/sms/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSmsCache is a mock of SmsCache interface.
type MockSmsCache struct {
	ctrl     *gomock.Controller
	recorder *MockSmsCacheMockRecorder
	isgomock struct{}
}

// MockSmsCacheMockRecorder is the mock recorder for MockSmsCache.
type MockSmsCacheMockRecorder struct {
	mock *MockSmsCache
}

// NewMockSmsCache creates a new mock instance.
func NewMockSmsCache(ctrl *gomock.Controller) *MockSmsCache {
	mock := &MockSmsCache{ctrl: ctrl}
	mock.recorder = &MockSmsCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmsCache) EXPECT() *MockSmsCacheMockRecorder {
	return m.recorder
}

// ReleaseRateLimit mocks base method.
func (m *MockSmsCache) ReleaseRateLimit(ctx context.Context, phone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseRateLimit", ctx, phone)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseRateLimit indicates an expected call of ReleaseRateLimit.
func (mr *MockSmsCacheMockRecorder) ReleaseRateLimit(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseRateLimit", reflect.TypeOf((*MockSmsCache)(nil).ReleaseRateLimit), ctx, phone)
}

// Retrieve mocks base method.
func (m *MockSmsCache) Retrieve(ctx context.Context, phone string, purpose domain.SmsPurpose) (*domain.SmsCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retrieve", ctx, phone, purpose)
	ret0, _ := ret[0].(*domain.SmsCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retrieve indicates an expected call of Retrieve.
func (mr *MockSmsCacheMockRecorder) Retrieve(ctx, phone, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockSmsCache)(nil).Retrieve), ctx, phone, purpose)
}

// Store mocks base method.
func (m *MockSmsCache) Store(ctx context.Context, code *domain.SmsCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockSmsCacheMockRecorder) Store(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockSmsCache)(nil).Store), ctx, code)
}

// TryReserveRateLimit mocks base method.
func (m *MockSmsCache) TryReserveRateLimit(ctx context.Context, phone string, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryReserveRateLimit", ctx, phone, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryReserveRateLimit indicates an expected call of TryReserveRateLimit.
func (mr *MockSmsCacheMockRecorder) TryReserveRateLimit(ctx, phone, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryReserveRateLimit", reflect.TypeOf((*MockSmsCache)(nil).TryReserveRateLimit), ctx, phone, ttl)
}

// VerifyAndConsume mocks base method.
func (m *MockSmsCache) VerifyAndConsume(ctx context.Context, phone string, purpose domain.SmsPurpose, input string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAndConsume", ctx, phone, purpose, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyAndConsume indicates an expected call of VerifyAndConsume.
func (mr *MockSmsCacheMockRecorder) VerifyAndConsume(ctx, phone, purpose, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAndConsume", reflect.TypeOf((*MockSmsCache)(nil).VerifyAndConsume), ctx, phone, purpose, input)
}
